-- MySQL Script generated by MySQL Workbench
-- Wed Nov  6 15:45:39 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`DORMITORY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DORMITORY` (
  `Id` VARCHAR(5) NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Number_of_room` INT NULL AUTO_INCREMENT,
  `Max_number_of_residence` INT NULL,
  `Description` VARCHAR(45) NULL,
  `Admin_ssn` VARCHAR(13) NULL,
  `Electricity_rate` DOUBLE NULL,
  `Water_rate` DOUBLE NULL,
  `Room_rate` DOUBLE NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ROOM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ROOM` (
  `Id` VARCHAR(5) NOT NULL,
  `Max_number_of_residence` INT NULL,
  `DORMITORY_Id` VARCHAR(5) NOT NULL,
  `Electricity_used` DOUBLE NULL,
  `Water_used` DOUBLE NULL,
  `ROOMcol` VARCHAR(45) NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_ROOM_DORMITORY_idx` (`DORMITORY_Id` ASC) VISIBLE,
  CONSTRAINT `fk_ROOM_DORMITORY`
    FOREIGN KEY (`DORMITORY_Id`)
    REFERENCES `mydb`.`DORMITORY` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FURNITURE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FURNITURE` (
  `Id` VARCHAR(5) NOT NULL,
  `type` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  `ROOM_Id` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`Id`, `ROOM_Id`),
  INDEX `fk_FURNITURE_ROOM1_idx` (`ROOM_Id` ASC) VISIBLE,
  CONSTRAINT `fk_FURNITURE_ROOM1`
    FOREIGN KEY (`ROOM_Id`)
    REFERENCES `mydb`.`ROOM` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`STUDENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`STUDENT` (
  `Id` VARCHAR(10) NOT NULL,
  `Faculty` VARCHAR(45) NOT NULL,
  `Degree_of_education` VARCHAR(45) NULL,
  `Room_entry_date` DATE NULL,
  `Total_activity_point` INT NULL,
  `University_entry_semester_year` VARCHAR(6) NULL,
  `First_name` VARCHAR(45) NULL,
  `Last_name` VARCHAR(45) NULL,
  `Birthdate` DATE NULL,
  `ROOM_Id` VARCHAR(5) NOT NULL,
  `Phone_number` VARCHAR(10) NULL,
  `STUDENTcol` VARCHAR(45) NULL,
  PRIMARY KEY (`Id`, `ROOM_Id`),
  INDEX `fk_STUDENT_ROOM1_idx` (`ROOM_Id` ASC) VISIBLE,
  CONSTRAINT `fk_STUDENT_ROOM1`
    FOREIGN KEY (`ROOM_Id`)
    REFERENCES `mydb`.`ROOM` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PARENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PARENT` (
  `Ssn` VARCHAR(13) NOT NULL,
  `First_name` VARCHAR(45) NULL,
  `Last_name` VARCHAR(45) NULL,
  `Phone_number` VARCHAR(10) NULL,
  `Age` INT NULL,
  `Birthdate` DATE NULL,
  `Address` VARCHAR(45) NULL,
  `STUDENT_Id` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`Ssn`),
  INDEX `fk_PARENT_STUDENT1_idx` (`STUDENT_Id` ASC) VISIBLE,
  CONSTRAINT `fk_PARENT_STUDENT1`
    FOREIGN KEY (`STUDENT_Id`)
    REFERENCES `mydb`.`STUDENT` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EMPLOYEE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EMPLOYEE` (
  `Ssn` VARCHAR(13) NOT NULL,
  `First_name` VARCHAR(45) NULL,
  `Last_name` VARCHAR(45) NULL,
  `Phone_number` INT NULL,
  `Age` INT NULL,
  `Birthdate` DATE NULL,
  `Position` VARCHAR(45) NULL,
  `Address` VARCHAR(45) NULL,
  `Start_date` DATE NULL,
  `DORMITORY_Id` INT NOT NULL,
  PRIMARY KEY (`Ssn`, `DORMITORY_Id`),
  INDEX `fk_EMPLOYEE_DORMITORY1_idx` (`DORMITORY_Id` ASC) VISIBLE,
  CONSTRAINT `fk_EMPLOYEE_DORMITORY1`
    FOREIGN KEY (`DORMITORY_Id`)
    REFERENCES `mydb`.`DORMITORY` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ACTIVITY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ACTIVITY` (
  `Id` VARCHAR(5) NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Semester` INT NULL,
  `Description` VARCHAR(45) NULL,
  `Point` INT NULL,
  `Max_number_of_student` INT NULL,
  `Start_date` DATE NULL,
  `End_date` DATE NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`VISITOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`VISITOR` (
  `Ssn` VARCHAR(13) NOT NULL,
  `First_name` VARCHAR(45) NULL,
  `Last_name` VARCHAR(45) NULL,
  `Phone_number` INT NULL,
  `Address` VARCHAR(45) NULL,
  `Birthdate` DATE NULL,
  `Relation` VARCHAR(45) NULL,
  `Date` DATE NULL,
  `Reason` VARCHAR(45) NULL,
  `STUDENT_Id` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`Ssn`),
  INDEX `fk_VISITOR_STUDENT1_idx` (`STUDENT_Id` ASC) VISIBLE,
  CONSTRAINT `fk_VISITOR_STUDENT1`
    FOREIGN KEY (`STUDENT_Id`)
    REFERENCES `mydb`.`STUDENT` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PAYMENT_HISTORY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PAYMENT_HISTORY` (
  `Invoice_id` VARCHAR(5) NOT NULL,
  `Status` VARCHAR(45) NULL,
  `STUDENT_Id` VARCHAR(10) NOT NULL,
  `Electricity_cost` DOUBLE NULL,
  `Water_cost` DOUBLE NULL,
  `Room_rental` DOUBLE NULL,
  `Total_cost` DOUBLE NULL,
  `Date_time_inform` DATETIME NULL,
  `Date_time_paid` DATETIME NULL,
  `Month_year` VARCHAR(45) NULL,
  PRIMARY KEY (`Invoice_id`),
  INDEX `fk_PAYMENT_HISTORY_STUDENT1_idx` (`STUDENT_Id` ASC) VISIBLE,
  CONSTRAINT `fk_PAYMENT_HISTORY_STUDENT1`
    FOREIGN KEY (`STUDENT_Id`)
    REFERENCES `mydb`.`STUDENT` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`WORK_HISTORY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`WORK_HISTORY` (
  `Ssn` VARCHAR(13) NOT NULL,
  `Position` VARCHAR(45) NULL,
  `Start_date` DATE NULL,
  `End_date` DATE NULL,
  `EMPLOYEE_Ssn` INT NOT NULL,
  `EMPLOYEE_DORMITORY_Id` INT NOT NULL,
  PRIMARY KEY (`Ssn`, `EMPLOYEE_Ssn`, `EMPLOYEE_DORMITORY_Id`),
  INDEX `fk_WORK_HISTORY_EMPLOYEE1_idx` (`EMPLOYEE_Ssn` ASC, `EMPLOYEE_DORMITORY_Id` ASC) VISIBLE,
  CONSTRAINT `fk_WORK_HISTORY_EMPLOYEE1`
    FOREIGN KEY (`EMPLOYEE_Ssn` , `EMPLOYEE_DORMITORY_Id`)
    REFERENCES `mydb`.`EMPLOYEE` (`Ssn` , `DORMITORY_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ATTEND_HISTORY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ATTEND_HISTORY` (
  `Date_time` DATETIME NOT NULL,
  `Type` VARCHAR(45) NULL,
  `STUDENT_Id` VARCHAR(10) NOT NULL,
  `STUDENT_ROOM_Id` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`Date_time`),
  INDEX `fk_ATTEND_HISTORY_STUDENT1_idx` (`STUDENT_Id` ASC, `STUDENT_ROOM_Id` ASC) VISIBLE,
  CONSTRAINT `fk_ATTEND_HISTORY_STUDENT1`
    FOREIGN KEY (`STUDENT_Id` , `STUDENT_ROOM_Id`)
    REFERENCES `mydb`.`STUDENT` (`Id` , `ROOM_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`REQUEST_HISTORY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`REQUEST_HISTORY` (
  `Id` VARCHAR(5) NOT NULL,
  `Date_time` DATETIME NULL,
  `Type` VARCHAR(45) NULL,
  `Status` VARCHAR(45) NULL,
  `Description` VARCHAR(45) NULL,
  `STUDENT_Id` VARCHAR(10) NOT NULL,
  `EMPLOYEE_Ssn` VARCHAR(13) NULL,
  `EMPLOYEE_DORMITORY_Id` VARCHAR(5) NULL,
  PRIMARY KEY (`Id`, `EMPLOYEE_Ssn`, `EMPLOYEE_DORMITORY_Id`),
  INDEX `fk_REQUEST_HISTORY_STUDENT1_idx` (`STUDENT_Id` ASC) VISIBLE,
  INDEX `fk_REQUEST_HISTORY_EMPLOYEE1_idx` (`EMPLOYEE_Ssn` ASC, `EMPLOYEE_DORMITORY_Id` ASC) VISIBLE,
  CONSTRAINT `fk_REQUEST_HISTORY_STUDENT1`
    FOREIGN KEY (`STUDENT_Id`)
    REFERENCES `mydb`.`STUDENT` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_REQUEST_HISTORY_EMPLOYEE1`
    FOREIGN KEY (`EMPLOYEE_Ssn` , `EMPLOYEE_DORMITORY_Id`)
    REFERENCES `mydb`.`EMPLOYEE` (`Ssn` , `DORMITORY_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Do`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Do` (
  `ACTIVITY_Id` VARCHAR(5) NOT NULL,
  `STUDENT_Id` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`ACTIVITY_Id`, `STUDENT_Id`),
  INDEX `fk_ACTIVITY_has_STUDENT_STUDENT1_idx` (`STUDENT_Id` ASC) VISIBLE,
  INDEX `fk_ACTIVITY_has_STUDENT_ACTIVITY1_idx` (`ACTIVITY_Id` ASC) VISIBLE,
  CONSTRAINT `fk_ACTIVITY_has_STUDENT_ACTIVITY1`
    FOREIGN KEY (`ACTIVITY_Id`)
    REFERENCES `mydb`.`ACTIVITY` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ACTIVITY_has_STUDENT_STUDENT1`
    FOREIGN KEY (`STUDENT_Id`)
    REFERENCES `mydb`.`STUDENT` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ACTIVITY_HISTORY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ACTIVITY_HISTORY` (
  `date_time` DATE NOT NULL,
  `STUDENT_Id` VARCHAR(10) NOT NULL,
  `ACTIVITY_Id` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`date_time`, `STUDENT_Id`, `ACTIVITY_Id`),
  INDEX `fk_ACTIVITY_HISTORY_STUDENT1_idx` (`STUDENT_Id` ASC) VISIBLE,
  CONSTRAINT `fk_ACTIVITY_HISTORY_STUDENT1`
    FOREIGN KEY (`STUDENT_Id`)
    REFERENCES `mydb`.`STUDENT` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
